blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/ThinkDenominator/gtregression/discussions
    about: Ask questions and share ideas in Discussions instead of creating an issue.
