#' Modify Regression Table Labels and Layout
#'
#' Allows customization of variable names, level labels, column headers, captions, and display options in regression summary tables.
#' Designed for use with tables generated by `gtsummary` functions such as `uni_reg()` or `multi_reg()`.
#'
#' @param gt_table A `gtsummary` table object (e.g., from `uni_reg()`, `multi_reg()`, etc.).
#' @param variable_labels A named vector to relabel variable names. Names must match model variable names.
#' @param level_labels A named vector to relabel levels of categorical variables.
#' @param header_labels A named vector to relabel table column headers. Names must match internal column names (e.g., `"estimate"`, `"p.value"`).
#' @param caption A character string to add a caption (table title).
#' @param bold_labels Logical. If `TRUE`, variable labels are bolded. Default is `FALSE`.
#' @param bold_levels Logical. If `TRUE`, factor level labels are bolded. Default is `FALSE`.
#' @param remove_N Logical. If `TRUE`, hides the sample size column (`N`) in univariate regression tables (`uni_reg`, `uni_reg_nbin`). Ignored for multivariate tables with a warning.
#' @param remove_N_obs Logical. If `TRUE`, removes source note showing complete-case sample size in multivariate regression tables (`multi_reg`, `multi_reg_nbin`). Ignored for univariate tables with a warning.
#' @param remove_abbreviations Logical. If `TRUE`, removes abbreviations showing expansions of effect size and confidence interval for all regression table outputs
#' @param caveat A character string to add as a source note below the table (e.g., "N may vary due to missing data."). This is always applied regardless of table type.
#'
#' @return A customized `gtsummary` table object with modified labels, layout, and options.
#'
#' @examples
#' \dontrun{
#' library(gtregression)
#' tbl_custom <- modify_table(
#'   uni_rr,
#'   variable_labels = c(age_cat = "Age", bmi = "BMI"),
#'   level_labels = c(`Young` = "Young Adults", `Old` = "Older Adults"),
#'   header_labels = c(estimate = "**Risk Ratio**", `p.value` = "***P*-value**"),
#'   caption = "Table 1: Univariate Regression",
#'   bold_labels = TRUE,
#'   remove_N = TRUE,
#'   caveat = "N may vary due to missing data."
#' )
#' }
#'
#' @importFrom gtsummary modify_table_body modify_header modify_caption bold_labels bold_levels modify_column_hide remove_source_note modify_source_note
#' @importFrom dplyr mutate case_when
#' @export
modify_table <- function(gt_table,
                         variable_labels = NULL,
                         level_labels = NULL,
                         header_labels = NULL,
                         caption = NULL,
                         bold_labels = FALSE,
                         bold_levels = FALSE,
                         remove_N = FALSE,
                         remove_N_obs = FALSE,
                         remove_abbreviations = FALSE,
                         caveat = NULL) {
  if (!requireNamespace("gtsummary", quietly = TRUE)) stop("Package 'gtsummary' is required.")
  if (!requireNamespace("dplyr", quietly = TRUE)) stop("Package 'dplyr' is required.")

  tbl <- gt_table

  # Detect source type from attribute
  source_type <- attr(tbl, "source")

  # 1. Variable labels
  if (!is.null(variable_labels)) {
    tbl <- gtsummary::modify_table_body(tbl, ~ dplyr::mutate(.x,
                                                             label = dplyr::case_when(
                                                               row_type == "label" & variable %in% names(variable_labels) ~ variable_labels[variable],
                                                               TRUE ~ label
                                                             )
    ))
  }

  # 2. Level labels
  if (!is.null(level_labels)) {
    tbl <- gtsummary::modify_table_body(tbl, ~ dplyr::mutate(.x,
                                                             label = dplyr::case_when(
                                                               row_type == "level" & label %in% names(level_labels) ~ level_labels[label],
                                                               TRUE ~ label
                                                             )
    ))
  }

  # 3. Header labels
  if (!is.null(header_labels)) {
    tbl <- gtsummary::modify_header(tbl, !!!header_labels)
  }

  # 4. Caption
  if (!is.null(caption)) {
    tbl <- gtsummary::modify_caption(tbl, caption)
  }

  # 5. Bold labels
  if (isTRUE(bold_labels)) {
    tbl <- gtsummary::bold_labels(tbl)
  }

  # 6. Bold levels
  if (isTRUE(bold_levels)) {
    tbl <- gtsummary::bold_levels(tbl)
  }

  # 7. Remove N only if univariate table
  if (isTRUE(remove_N)) {
    if (source_type %in% c("uni_reg", "uni_reg_nbin")) {
      tbl <- gtsummary::modify_column_hide(tbl, stat_n)
    } else {
      warning("remove_N is only applicable to univariate regression tables (uni_*). Ignored.")
    }
  }

  # 8. Remove source note only if multivariate
  if (isTRUE(remove_N_obs)) {
    if (source_type %in% c("multi_reg", "multi_reg_nbin")) {
      tbl <- gtsummary::remove_source_note(tbl)
    } else {
      warning("remove_N_obs is only applicable to multivariate regression tables (multi_*). Ignored.")
    }
  }


  # 9. Add caveat below existing source notes
  if (!is.null(caveat)) {
    tbl <- gtsummary::modify_source_note(tbl, caveat)
  }
  # 10. Remove abbreviation footnote (both uni and multi)
  if (isTRUE(remove_abbreviations)) {
    tbl <- gtsummary::remove_abbreviation(tbl)
  }

  return(tbl)
}
