name: test-coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr

      - name: Run coverage and upload to Codecov
        # Skip on forked PRs (secrets aren't available there)
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}  # <-- paste full token into this repo's secret
        run: |
          Rscript -e 'covr::codecov(token = Sys.getenv("CODECOV_TOKEN"), quiet = FALSE)'
