name: test-coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write   # required by codecov-action v4 for tokenless uploads

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # ensure your package + deps + covr are installed
          extra-packages: |
            any::covr
            local::.

      - name: Run tests & create coverage.xml
        run: |
          Rscript -e 'cov <- covr::package_coverage(); covr::to_cobertura(cov, file = "coverage.xml"); cat("Wrote coverage.xml\n")'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: unittests
          name: github-actions
          fail_ci_if_error: true
